[package]
name = "croner"
version = "0.0.7"
edition = "2021"
license = "MIT"
description = "A cron parser and job scheduler library for Rust"
repository = "https://github.com/hexagon/croner-rust"
documentation = "https://docs.rs/croner"
readme = "README.md"
keywords = ["cron", "scheduler", "job", "task", "time"]
categories = ["date-and-time", "scheduling"]
homepage = "https://github.com/hexagon/croner-rust"

[lib]
name = "croner"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
threadpool = "1.8.1"  # Use the latest version available

[dev-dependencies]
chrono-tz = "0.8.4"
criterion = "0.3"

[[bench]]
name = "croner_bench"
harness = false