[package]
name = "croner"
version = "2.0.3"
edition = "2021"
license = "MIT"
description = "Fully-featured, lightweight, and efficient Rust library designed for parsing and evaluating cron patterns"
repository = "https://github.com/hexagon/croner-rust"
documentation = "https://docs.rs/croner"
readme = "README.md"
keywords = ["cron", "scheduler", "job", "task", "time"]
categories = ["date-and-time", "scheduling"]
homepage = "https://github.com/hexagon/croner-rust"

[lib]
name = "croner"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.31"

[dev-dependencies]
chrono-tz = "0.8.4"
criterion = "0.3"

[[bench]]
name = "croner_bench"
harness = false